apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-database
  labels:
    type: local
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
